# -*- coding: utf-8 -*-
"""Assignment 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rBRB4fEnjfQiddAHTqyUWXBYuyYdaXYX
"""

#Suchit Mudichintala
#CS 175

#Create a program that will count the numbers of times the letter T (uppercase or lowercase) appears in a string

#1. Get a string from the user.
userString = input("Enter a sentence: ")

#2. Create a variable to use to hold the count.
count = 0

#3. Count the Ts and print the result.

for char in userString:
  if char.lower() == "t":
    count += 1
print("The letter T appears", count, "times.")

#Create a program that will split date string and display each piece of the data

#Create a string with the date '11/26/2020'

date = '11/26/2020'

#Split the date.

date_parts = date.split("/")

#Display each piece of the date.

print("Month:", date_parts[0])
print("Day:", date_parts[1])
print("Year:", date_parts[2])

#Create a program that gets the user's first name, last name, and student ID number. Using this data, it generates a system login name.

#Get the first three letters of the first name. If the name is less than 3 charactesr, the slice will return the entire first name.

first_name = input("Enter your first name: ")

if len(first_name) < 3:
  first_name_slice = first_name
else:
  first_name_slice = first_name[:3]

#Get the first three letters of the last name. If the name is less than 3 characters, the slice will return the entire last name.

last_name = input("Enter your last name: ")

if len(last_name) < 3:
  last_name_slice = last_name
else:
  last_name_slice = last_name[:3]

#Get the last three characters of the student ID. If the ID number is less than 3 characters, the slice will return the entire ID number.

student_id = input("Enter your student ID number: ")

if len(student_id) < 3:
  student_id_slice = student_id
else:
  student_id_slice = student_id[-3:]

#4.	Put the sets of characters together.

login_name = first_name_slice + last_name_slice + student_id_slice

#5.	Return the login name.

print("Your login name is:", login_name)

# Create a program to determine whether all of the requirements are met for a valid password.

password = input("Please enter your password: ")
correct_length = False
has_uppercase = False
has_lowercase = False
has_digit = False

if len(password) >= 7:
    correct_length = True
    for char in password:
        if char.isupper():
            has_uppercase = True
        elif char.islower():
            has_lowercase = True
        elif char.isdigit():
            has_digit = True

if correct_length and has_uppercase and has_lowercase and has_digit:
    valid = True
else:
    valid = False

print(valid)