# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1seUvfpDwYmUlkPkh4a_svw6CIom2FGVQ
"""

# CS175-50
#Suchit Mudichintala

print("I'm in the class")
print(8+6)
print("My major is Computer Science")